Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "1"
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.boot_timeout = 600
  config.vm.network "private_network", ip: "192.168.1.5"
  config.vm.hostname = "hw-10-5"
end